#!/usr/bin/env bash
#
# Only2Bali — one-shot Postgres bootstrap for the Hostinger VPS.
#
#   sudo bash bootstrap.sh db.only2bali.com
#
# Brings up PostgreSQL 17 in Docker with mutual TLS, applies the schema, seeds
# the catalogue, verifies the result, and prints the three values to paste into
# Vercel. Everything runs on this machine; no password leaves it.
#
# Safe to re-run: it skips work that is already done rather than redoing it.

set -euo pipefail

DB_HOST="${1:-}"
if [ -z "$DB_HOST" ]; then
  cat >&2 <<'USAGE'
usage: bootstrap.sh <database-hostname>

  The hostname must be one that resolves to this server and that the app will
  dial, e.g. db.only2bali.com. It is baked into the server certificate, so a
  mismatch makes every connection fail verification.

  Add the DNS A record and let it propagate before running this.
USAGE
  exit 1
fi

HERE="$(cd "$(dirname "$0")" && pwd)"
INFRA="$(cd "$HERE/.." && pwd)"
ENV_FILE="$INFRA/.env"
COMPOSE="docker compose --env-file $ENV_FILE -f $INFRA/docker-compose.yml"

say()  { printf '\n\033[1;36m==>\033[0m %s\n' "$1"; }
ok()   { printf '    \033[1;32mok\033[0m  %s\n' "$1"; }
warn() { printf '    \033[1;33m!!\033[0m  %s\n' "$1"; }
die()  { printf '\n\033[1;31mfailed:\033[0m %s\n' "$1" >&2; exit 1; }

# ---------------------------------------------------------------- preflight --
say "Preflight"

command -v docker >/dev/null 2>&1 || die "Docker is not installed. curl -fsSL https://get.docker.com | sudo sh"
docker compose version >/dev/null 2>&1 || die "docker compose plugin missing"
command -v openssl >/dev/null 2>&1 || die "openssl is not installed"
ok "docker $(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"

RESOLVED="$(getent hosts "$DB_HOST" 2>/dev/null | awk '{print $1}' | head -1 || true)"
if [ -z "$RESOLVED" ]; then
  warn "$DB_HOST does not resolve yet. Certificates will still be generated,"
  warn "but Vercel cannot reach it until the DNS A record exists."
else
  ok "$DB_HOST resolves to $RESOLVED"
fi

# ------------------------------------------------------------------- config --
say "Configuration"

if [ -f "$ENV_FILE" ]; then
  ok ".env already exists, keeping it"
else
  PASSWORD="$(openssl rand -base64 36 | tr -d '/+=' | cut -c1-40)"
  cat > "$ENV_FILE" <<EOF
# Generated by bootstrap.sh on $(date -u +%FT%TZ). Keep this file secret.
POSTGRES_USER=only2bali_app
POSTGRES_PASSWORD=${PASSWORD}
POSTGRES_DB=only2bali
POSTGRES_PORT=5432
BACKUP_RETENTION_DAYS=14
EOF
  chmod 600 "$ENV_FILE"
  ok "generated a 40-character password into .env (chmod 600)"
fi

# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

# pg_hba.conf requires scram-sha-256 even on the container's own unix socket —
# there is deliberately no `trust` line. So every psql call below needs the
# password. Exported rather than passed as `-e PGPASSWORD=value`, so that it is
# handed to the container through the environment and never appears in `ps`.
export PGPASSWORD="$POSTGRES_PASSWORD"

mkdir -p "$HERE/backups" && chmod 700 "$HERE/backups"
chmod +x "$HERE/backup.sh" 2>/dev/null || true

# ------------------------------------------------------------- certificates --
say "Certificates (mutual TLS)"

if [ -f "$HERE/certs/ca.key" ]; then
  ok "certs/ already exists, not regenerating"
else
  chmod +x "$HERE/generate-certs.sh"
  "$HERE/generate-certs.sh" "$DB_HOST" >/dev/null
  ok "created CA, server and client certificates for $DB_HOST"
fi

# postgres:17-alpine runs as uid 70. Getting this wrong makes Postgres refuse
# to start with "private key file must be owned by the database user or root".
chown 70:70 "$HERE/certs/server.key" "$HERE/certs/server.crt" "$HERE/certs/ca.crt" 2>/dev/null \
  || warn "could not chown certs — run this script with sudo"
chmod 600 "$HERE/certs/server.key"
ok "certificate ownership set to uid 70"

# ------------------------------------------------------------------ startup --
say "Starting PostgreSQL"

$COMPOSE up -d
printf '    waiting for readiness'
for _ in $(seq 1 60); do
  if $COMPOSE exec -T postgres pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
    printf '\n'; ok "postgres is accepting connections"; break
  fi
  printf '.'; sleep 2
done
$COMPOSE exec -T postgres pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1 \
  || { $COMPOSE logs --tail=30 postgres; die "postgres did not become ready"; }

SSL_ON="$($COMPOSE exec -T -e PGPASSWORD postgres psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc 'show ssl' | tr -d '\r')"
[ "$SSL_ON" = "on" ] && ok "TLS is enabled" || die "TLS is NOT enabled — check certs/ and pg_hba.conf"

# ------------------------------------------------------------------- schema --
say "Schema"

psql_run() { $COMPOSE exec -T -e PGPASSWORD postgres psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" "$@"; }

MIGRATIONS="$INFRA/../only2bali-next/lib/db/migrations"
JOURNAL="$MIGRATIONS/meta/_journal.json"
[ -f "$JOURNAL" ] || die "migration journal not found at $JOURNAL"

# Every migration is plain SQL, so this box needs no Node toolchain — but it
# must track what it has applied, or a second migration would never run and a
# first one would run twice. It writes the same ledger drizzle-kit uses (hash
# of the file, and the journal's own timestamp), so either tool can be pointed
# at this database afterwards and will agree about what is already applied.
psql_run -q -c "create schema if not exists drizzle" \
  -c "create table if not exists drizzle.__drizzle_migrations (
        id serial primary key, hash text not null, created_at bigint)" \
  || die "could not create the migration ledger"

# `tag<TAB>when` per journal entry, in order. Plain awk so no jq is required.
ENTRIES="$(awk '
  /"when"/ { gsub(/[^0-9]/, "", $0); w = $0 }
  /"tag"/  { gsub(/.*"tag"[^"]*"|",?$/, "", $0); print $0 "\t" w }
' "$JOURNAL")"

APPLIED_ANY=0
PRE_EXISTING="$(psql_run -tAc "select to_regclass('public.account') is not null" | tr -d '\r')"
LEDGER_ROWS="$(psql_run -tAc "select count(*) from drizzle.__drizzle_migrations" | tr -d '\r')"

# Read the journal on fd 3, not on stdin.
#
# `docker compose exec -T` consumes its own stdin. With the loop reading from
# stdin, the very first psql call swallowed the rest of the heredoc, so the
# loop ran exactly once: 0000 applied, 0001 silently never seen, and the script
# still exited 0. Observed on the VPS on 2026-07-23 — 41 tables where 43 were
# expected, with no error anywhere.
while IFS="$(printf '\t')" read -r TAG WHEN <&3; do
  [ -n "$TAG" ] || continue
  FILE="$MIGRATIONS/$TAG.sql"
  [ -f "$FILE" ] || die "migration $TAG named in the journal but missing on disk"
  HASH="$(sha256sum "$FILE" | cut -d' ' -f1)"

  SEEN="$(psql_run -tAc "select count(*) from drizzle.__drizzle_migrations where hash = '$HASH'" | tr -d '\r')"
  if [ "${SEEN:-0}" -gt 0 ]; then
    ok "$TAG already applied"
    continue
  fi

  # A database bootstrapped before this ledger existed already has the initial
  # schema. Record it rather than replaying it onto live tables.
  if [ "$PRE_EXISTING" = "t" ] && [ "${LEDGER_ROWS:-0}" -eq 0 ] && [ "$TAG" = "0000_initial_schema" ]; then
    psql_run -q -c "insert into drizzle.__drizzle_migrations (hash, created_at) values ('$HASH', $WHEN)"
    ok "$TAG adopted (schema was already present)"
    continue
  fi

  # Drizzle separates statements with --> statement-breakpoint; psql does not
  # care, but strip it so the file reads cleanly in the logs.
  sed 's|^--> statement-breakpoint$||' "$FILE" | psql_run -q -f - \
    || die "$TAG failed to apply"
  psql_run -q -c "insert into drizzle.__drizzle_migrations (hash, created_at) values ('$HASH', $WHEN)"
  ok "$TAG applied"
  APPLIED_ANY=1
done 3<<EOF
$ENTRIES
EOF

TABLES="$(psql_run -tAc "select count(*) from information_schema.tables where table_schema='public'" | tr -d '\r')"
[ "$APPLIED_ANY" -eq 1 ] && ok "schema now at $TABLES tables" || ok "schema up to date ($TABLES tables)"

# The loop above failing quietly is the failure mode that cost us a run, so
# assert rather than trust it: every migration named in the journal must now
# have a row in the ledger.
JOURNAL_COUNT="$(printf '%s\n' "$ENTRIES" | grep -c . || true)"
LEDGER_COUNT="$(psql_run -tAc "select count(*) from drizzle.__drizzle_migrations" | tr -d '\r')"
[ "${LEDGER_COUNT:-0}" -eq "${JOURNAL_COUNT:-0}" ] \
  || die "journal lists $JOURNAL_COUNT migrations but only $LEDGER_COUNT are applied"
ok "$LEDGER_COUNT of $JOURNAL_COUNT migrations applied"

# --------------------------------------------------------------------- seed --
say "Catalogue"

CIRCUITS="$(psql_run -tAc 'select count(*) from circuit' | tr -d '\r')"
if [ "$CIRCUITS" -gt 0 ]; then
  ok "catalogue already seeded ($CIRCUITS circuits), skipping"
else
  psql_run -q -f - < "$HERE/seed.sql" || die "seed failed"
  ok "catalogue seeded"
fi

# ------------------------------------------------------------------- verify --
say "Verification"

psql_run -tA <<'SQL' | while IFS='|' read -r label value; do printf '    %-34s %s\n' "$label" "$value"; done
select 'tables', count(*)::text from information_schema.tables where table_schema='public'
union all select 'enums', count(*)::text from pg_type where typtype='e'
union all select 'check constraints', count(*)::text from pg_constraint where contype='c' and connamespace='public'::regnamespace
union all select 'circuits', count(*)::text from circuit
union all select 'packages published', count(*)::text from package where status='published'
union all select 'departures upcoming', count(*)::text from departure where start_date >= current_date
union all select 'meals rated', count(*)::text from package_day_meal;
SQL

# The business rules must be refused by Postgres, not merely by the app.
RULE_OK=0
if ! psql_run -q -c "insert into trip_request (protocol, group_size, cook_required) values ('jain', 4, true)" >/dev/null 2>&1; then
  RULE_OK=$((RULE_OK+1))
fi
if ! psql_run -q -c "insert into trip_request (protocol, group_size, visibility, mobile_verified) values ('vegan', 2, 'open_to_verified', false)" >/dev/null 2>&1; then
  RULE_OK=$((RULE_OK+1))
fi
[ "$RULE_OK" -eq 2 ] && ok "business rules are enforced by the database" \
                     || warn "a constraint did not fire — inspect the schema"

# ------------------------------------------------------------------ exposure --
say "Exposure check"

if command -v ufw >/dev/null 2>&1; then
  ufw status 2>/dev/null | grep -q "${POSTGRES_PORT}/tcp" \
    && ok "ufw allows ${POSTGRES_PORT}/tcp" \
    || warn "ufw does not allow ${POSTGRES_PORT}/tcp — Vercel will not connect. sudo ufw allow ${POSTGRES_PORT}/tcp"
else
  warn "ufw not installed; make sure port ${POSTGRES_PORT} is reachable"
fi
ok "connections require a client certificate (clientcert=verify-full)"

# ------------------------------------------------------------------ handoff --
b64() { base64 -w0 "$1" 2>/dev/null || base64 "$1" | tr -d '\n'; }

cat <<EOF


================================================================================
  Paste these into Vercel  →  Project only2bali  →  Settings  →  Environment
  Variables. Set each for Production (and Preview if you want previews to work).
================================================================================

DATABASE_URL
postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

PGSSL_CA
$(b64 "$HERE/certs/ca.crt")

PGSSL_CERT
$(b64 "$HERE/certs/client.crt")

PGSSL_KEY
$(b64 "$HERE/certs/client.key")

================================================================================

Then, on this machine, remove the client key — only Vercel needs it, and a
client key sitting beside the database defeats the point of having one:

    shred -u $HERE/certs/client.key $HERE/certs/client.crt

Keep certs/ca.key safe and offline. It is what issues replacement client
certificates. If it leaks, anyone can mint a client and the mTLS is worthless.

Verify from your laptop that a password alone is NOT enough:

    psql "postgres://${POSTGRES_USER}:PASSWORD@${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require"
    # expected: FATAL: connection requires a valid client certificate

================================================================================
EOF
