#!/usr/bin/env bash
#
# Only2Bali — start everything locally so you can click around.
#
#   npm run dev:local
#
# Starts Postgres in Docker, applies the schema, seeds the catalogue, generates
# a local AUTH_SECRET, and runs the dev server. Nothing here touches production
# and no real credentials are involved.
#
# Stop it with Ctrl-C. The database keeps its data; run `npm run dev:down` to
# remove it entirely.

set -euo pipefail

CONTAINER="o2b-local-db"
PORT="${O2B_DB_PORT:-55432}"
URL="postgres://only2bali_app:localdev@127.0.0.1:${PORT}/only2bali"

cd "$(dirname "$0")/.."

say() { printf '\n\033[1;36m==>\033[0m %s\n' "$1"; }
ok()  { printf '    \033[1;32mok\033[0m  %s\n' "$1"; }

command -v docker >/dev/null 2>&1 || {
  echo "Docker is not running or not installed. Start Docker Desktop and try again." >&2
  exit 1
}

# Pick a port that is actually free. Developers commonly have something else on
# 3000 already, and Next.js failing with EADDRINUSE after a successful database
# setup is a confusing way to find that out.
find_free_port() {
  node -e '
    const net = require("net");
    const candidates = [3000, 3100, 3200, 3300, 3400, 3500];
    (async () => {
      for (const p of candidates) {
        // Listen with no host, exactly as Next.js does, so the probe binds "::"
        // and collides the same way. Probing 127.0.0.1 alone reports a port as
        // free when another server already holds it on "::".
        const free = await new Promise((res) => {
          const s = net.createServer();
          s.once("error", () => res(false));
          s.once("listening", () => s.close(() => res(true)));
          s.listen(p);
        });
        if (free) { console.log(p); return; }
      }
      console.log(0);
    })();
  ' 2>/dev/null || echo 0
}

if [ -n "${PORT_APP:-}" ]; then
  APP_PORT="$PORT_APP"
else
  APP_PORT="$(find_free_port)"
  if [ "$APP_PORT" = "0" ] || [ -z "$APP_PORT" ]; then
    echo "Could not find a free port between 3000 and 3500. Set PORT_APP=<port> and retry." >&2
    exit 1
  fi
fi

if [ "$APP_PORT" != "3000" ]; then
  printf '
    note: port 3000 is in use by something else, using %s instead
' "$APP_PORT"
fi

say "Database"
if [ "$(docker inspect -f '{{.State.Running}}' "$CONTAINER" 2>/dev/null)" = "true" ]; then
  ok "container $CONTAINER already running on port $PORT"
elif docker inspect "$CONTAINER" >/dev/null 2>&1; then
  docker start "$CONTAINER" >/dev/null
  ok "restarted existing container $CONTAINER"
else
  docker run -d --name "$CONTAINER" \
    -p "${PORT}:5432" \
    -e POSTGRES_USER=only2bali_app \
    -e POSTGRES_PASSWORD=localdev \
    -e POSTGRES_DB=only2bali \
    postgres:17-alpine >/dev/null
  ok "created container $CONTAINER on port $PORT"
fi

printf '    waiting for postgres'
for _ in $(seq 1 45); do
  if docker exec "$CONTAINER" pg_isready -U only2bali_app -d only2bali >/dev/null 2>&1; then
    printf '\n'; ok "accepting connections"; break
  fi
  printf '.'; sleep 1
done
docker exec "$CONTAINER" pg_isready -U only2bali_app -d only2bali >/dev/null 2>&1 || {
  echo "postgres did not start; try: docker logs $CONTAINER" >&2; exit 1
}

say "Schema and catalogue"
TABLES=$(docker exec "$CONTAINER" psql -U only2bali_app -d only2bali -tAc \
  "select count(*) from information_schema.tables where table_schema='public'" | tr -d '\r')

if [ "${TABLES:-0}" -ge 41 ]; then
  ok "schema already applied ($TABLES tables)"
else
  DATABASE_URL="$URL" npx --yes drizzle-kit migrate >/dev/null 2>&1
  ok "schema applied"
fi

CIRCUITS=$(docker exec "$CONTAINER" psql -U only2bali_app -d only2bali -tAc \
  "select count(*) from circuit" | tr -d '\r')
if [ "${CIRCUITS:-0}" -gt 0 ]; then
  ok "catalogue already seeded ($CIRCUITS circuits)"
else
  DATABASE_URL="$URL" npx --yes tsx lib/db/seed.ts >/dev/null 2>&1
  ok "catalogue seeded"
fi

say "Local environment"
if [ -f .env.local ] && grep -q '^AUTH_SECRET=.\{32,\}' .env.local; then
  ok ".env.local already has an AUTH_SECRET, keeping it"
else
  SECRET=$(openssl rand -base64 48 2>/dev/null | tr -d '\n' || date +%s%N | sha256sum | head -c 64)
  cat > .env.local <<EOF
# Local development only. Generated by scripts/dev-up.sh — not for production.
DATABASE_URL=${URL}
AUTH_SECRET=${SECRET}
EOF
  ok "wrote .env.local"
fi

cat <<BANNER

================================================================================
  Ready. Open  http://localhost:${APP_PORT}
================================================================================

  To sign in — there is no password, by design:

    1. Click "Sign in" (top right), or go to
       http://localhost:${APP_PORT}/en/login

    2. Enter ANY email address, real or not. For example:
         loganathan@only2bali.com

    3. Your six-digit code is printed IN THIS TERMINAL, on a line like:
         [auth] OTP for loganathan@only2bali.com: 481902

    4. Type it in. You land on /en/account.

  The account is created on first sign-in — there is nothing to register.

  Try the other languages too:
    /hi  /ta  /gu  /te  /kn  /mr     (or use the globe in the nav)

  Codes expire in 10 minutes, work once, and lock after 5 wrong guesses.

  Stop with Ctrl-C.  Remove the database with: npm run dev:down

================================================================================

BANNER

exec npx next dev --port "$APP_PORT"
